Implement negative test for pipenv and micropipenv enabled in the same time

diff --git a/2.7/s2i/bin/assemble b/2.7/s2i/bin/assemble
--- a/2.7/s2i/bin/assemble
+++ b/2.7/s2i/bin/assemble
@@ -35,6 +35,12 @@ function install_tool() {
 
 set -e
 
+# First of all, check that we don't have disallowed combination of ENVs
+if [[ ! -z "$ENABLE_PIPENV" && ! -z "$ENABLE_PIPENV" ]]; then
+  echo "ERROR: Pipenv and micropipenv cannot be enabled at the same time!"
+  exit 1
+fi
+
 shopt -s dotglob
 echo "---> Installing application source ..."
 mv /tmp/src/* "$HOME"
diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -6,7 +6,7 @@
 # IMAGE_NAME specifies a name of the candidate image used for testing.
 # The image has to be available before this script is executed.
 #
-declare -a WEB_APPS=({standalone,setup,setup-requirements,django,numpy,app-home,npm-virtualenv-uwsgi,locale,mod-wsgi,pipenv{% if spec.version.startswith("3.") %},micropipenv,micropipenv-requirements{% endif %}}-test-app)
+declare -a WEB_APPS=({standalone,setup,setup-requirements,django,numpy,app-home,npm-virtualenv-uwsgi,locale,mod-wsgi,pipenv,pipenv-and-micropipenv-fails{% if spec.version.startswith("3.") %},micropipenv,micropipenv-requirements{% endif %}}-test-app)
 
 # TODO: Make command compatible for Mac users
 test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
@@ -85,8 +85,9 @@ cleanup() {
 
 check_result() {
   local result="$1"
-  if [[ "$result" != "0" ]]; then
-    info "TEST FAILED (${result})"
+  local expected=${2:-0}  # if not defined, we expect 0 as a return code
+  if [[ "$result" != "$expected" ]]; then
+    info "TEST FAILED, EXPECTED:${expected} GOT:${result}"
     cleanup
     exit $result
   fi
@@ -194,7 +195,14 @@ check_result $?
 for app in ${WEB_APPS[@]}; do
   prepare ${app}
   run_s2i_build ${app}
-  check_result $?
+  RESULT=$?
+  if [[ "$app" == "pipenv-and-micropipenv-fails-test-app" ]]; then
+    # This test should fail during a build
+    check_result $RESULT 125
+    continue
+  else
+    check_result $RESULT
+  fi
 
   # test application with default user
   test_application
